### ISSUE TITLE
Viseme Creation

### ISSUE THREAD

**Issue by Yusarina** [teamneoneko/Avatar-Toolkit#16]
Add Viseme creation, improve upon the current cats system if possible.

**Comment by 989onan** [comment]
Tuxedo does have a facial tracking one that works, maybe we should communicate with @feilen on that

**Comment by Yusarina** [comment]
We can totally do that!

**Comment by feilen** [comment]
It's up to y'all, not sure where the extra benefit would be in duplicating the functionality though?

**Comment by Yusarina** [comment]
Mhmm good point regarding the duplicating functionality, however I have a feeling some people may expect the feature in this tool kit as it's meant to be a Cats replacement @989onan what do you think?

**Comment by 989onan** [comment]
it might just be best to use the original thing of making the vrc ones and if they need facial tracking just direct them to install Tuxedo

**Comment by Yusarina** [comment]
Mhmm ok, do you think any improvement need to be made on the VRC one?

**Comment by 989onan** [comment]
uhmmm, I don't think so. It should be fine with the original cats system, seems to work fine

**Comment by Yusarina** [comment]
Sorry I meant original cats one lol, but ok awesome I will sort it over the next week then.

**Comment by Yusarina** [comment]
In progress - https://github.com/teamneoneko/Avatar-Toolkit/pull/27

**Comment by Yusarina** [comment]
On Hold unto Armature Selection is done so I can finish what is needed to be done.

**Comment by 989onan** [comment]
this is done, closing ^_^
