### ISSUE TITLE
Make a more complex merge doubles that allows for merging moving vertices on shapekeys but still prevent mouth fusing

### ISSUE THREAD

**Issue by 989onan** [teamneoneko/Avatar-Toolkit#41]
Basically if the user where to merge doubles on every shape key, but only merge ones that merge on every shapekey on the mesh
Much harder to do in code than one might expect, because tracking vertices that already poofed is difficult

**Comment by Yusarina** [comment]
Closed as PR Merge https://github.com/teamneoneko/Avatar-Toolkit/pull/42 which adds this.
