### ISSUE TITLE
Remove Doubles and Adavanced Remove Doubles Issues.

### ISSUE THREAD

**Issue by Yusarina** [teamneoneko/Avatar-Toolkit#54]
This is just an issue tracker for remove doubles, it may get updated as we find more issues.

1: Both advanced and normal remove doubles does nothing to inform the user that it's doing something, we need to add a notification and a loading thingy to make sure the user knows to wait. On larger models it can take a while and blender will appear like has crashed. 
2: Both are also very very slow on larger modals, even cats version seems to be faster on my testing modals. We need to see if we can improve this.

I want to say Advanced Remove doubles seems to take a VERY VERY long time on larger models, I been waiting 30 minutes for it to complete and it's still going, I can see it's doing stuff in the console, but it's taking a long time.

**Comment by 989onan** [comment]
yeah advanced remove doubles is destined to take an extremely long time. it's because of it's every single vertex mentality

**Comment by Yusarina** [comment]
Yea I understand that, but the user will 100% think blender has crashed as I thought this unto I looked at the console, we need to ensure the user knows to wait, if not we gonna get alot of "THIS DOESN'T WORK IT JUST CRASHES PLZZZ FIX" and if possible maybe improve the efficiency (Not sure if that is possible though).

**Comment by 989onan** [comment]
yeah, idk why the modal doesn't free the screen, since it should be able to free it every iteration

But yus, loading bar needs to be added

**Comment by Yusarina** [comment]
Warning has been added via https://github.com/teamneoneko/Avatar-Toolkit/pull/67 loading bar just does not working as blender locks up during this process so there is no point adding it. If we can figure out why it does that we can add it.

I have some ideas on how we could optimize this process however I hit some snags I see if I can work something out, for now this issue can be closed one the PR is merged.
