### ISSUE TITLE
Blender changed import toml to import tomllib

### ISSUE THREAD

**Issue by fang64** [teamneoneko/Avatar-Toolkit#79]
It seems for addons there was a change upstream at some point to switch to tomllib.

[Blender Upstream Repo Link about toml change](https://projects.blender.org/extensions/space_view3d_stored_views/commit/2e919c3f0bb718b94ee849b6890a3b066f2ea80f)

I tried to install from main branch, it failed until I modified,

core/addon_preferences.py

import toml > import tomllib

**Comment by Yusarina** [comment]
Solved in https://github.com/teamneoneko/Avatar-Toolkit/pull/80
